server:
  servlet:
    context-path: /spring-redis
  port: 8080

spring:
  cache:
    type: redis
    redis:
      use-key-prefix: true
  redis:
    port: 6379
    password: password
    host: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update