version: "3.8"

services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - spring-examples:/var/lib/redis
    container_name: redis
    networks:
      - redis-network
  app:
    depends_on:
      - redis-stack
    build: .
    image: spring-redis
    restart: on-failure
    container_name: spring-redis
    networks:
      - redis-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_REDIS_HOST=$REDIS_HOST
      - SPRING_REDIS_PORT=$REDIS_DOCKER_PORT
      - SPRING_REDIS_PASSWORD=$REDIS_PASSWORD


volumes:
  spring-examples:

networks:
  redis-network:
    driver: bridge